# -*- coding: utf-8 -*-
"""Advanced AI Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuA7Ys5TBDLVsF_B0wQsk3BYbgWug2lk

# **Advanced AI Chatbot**

## **Install Packages**
"""

# Installing packages

!pip install Flask pyngrok mistralai

import os
from flask import Flask, request, render_template_string, jsonify
from pyngrok import ngrok
from mistralai import Mistral
from getpass import getpass

# Create mistral and ngrok API Keys

mistral_api_key = getpass("Please enter your Mistral API Key: ")
ngrok_auth_token = getpass("Please enter your ngrok auth token: ")

"""## **Creating variables for AI Chatbot**"""

# Define the AI model
client = Mistral(api_key=mistral_api_key)
app = Flask(__name__)
port = 8000

# Design the AI Chatbot writing website content via html
html = """

<html>
  <title> Chatbot </title>
  <style>  .user { color:blue; }  </style>

  <body>
    <div id="chatbot"></div>
    <input id="input" placeholder="Type a message">
    <button onclick="send()"> Send </button>

    <script>
      function send() {
        const msg = document.getElementById('input').value;
        if (!msg) return

        add("You", msg, 'user')
        document.getElementById("input").value = ''
        fetch('./get_response', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({message:msg})})
        .then(res => res.json()).then(data => add('Bot', data.response, 'bot'))
      }

      function add(sender, msg, cls) {
        const div = document.createElement('div')
        div.className = `msg ${cls}`
        div.textContent = `${sender}: ${msg}`
        document.getElementById('chatbot').appendChild(div)
        document.getElementById('chatbot').scrollTop = document.getElementById('chatbot').scrollHeight
      }
    </script>
  </body>
</html>

"""
# Serving the website content
@app.route("/")
def index():
    return render_template_string(html)

# Call the AI model
@app.route('/get_response', methods= ["POST"])
def get_response():
    user_input = request.json.get('message', '')
    response = client.chat.complete(
        model="mistral-large-latest",
        messages=[
            {"role": 'user', "content": user_input}
        ])
    return jsonify({'response': response.choices[0].message.content})

# Run the code/app
if __name__ == "__main__":
    ngrok.set_auth_token("2sbiMydCSiKdCrMuGUlM90tpP79_7vhRJrWAvUHX2VfAo1Xrs")
    public_url = ngrok.connect(port)
    print(f"Chatbot running at: " +str(public_url))
    app.run(port=port)